In [7]:
import pandas as pd
import numpy as np

In [8]:
data = np.random.randn(4,3)

In [6]:
data

array([[-1.14938528e+00,  1.11758015e+00,  2.73085011e+00],
       [-1.91040173e-01, -1.72570283e-04,  1.07910168e+00],
       [ 7.43445747e-01, -9.51107243e-01,  2.55509955e-01],
       [-8.12931368e-01,  1.67615800e+00,  1.00672292e+00]])

In [70]:
dataFrame = pd.DataFrame(data)

In [71]:
dataFrame

          0         1         2
0  0.548051  1.295176 -0.761422
1  1.763184  0.209048  0.522082
2  0.968224 -0.000417  1.127900
3  0.060668 -1.168144  0.500326

In [72]:
dataFrame[0]

0    0.548051
1    1.763184
2    0.968224
3    0.060668
Name: 0, dtype: float64

In [73]:
type(dataFrame[0])

pandas.core.series.Series

In [74]:
yeniDataFrame = pd.DataFrame(data, index = ["Kadir","Atlas","Mehmet","Tugce"], columns = ["Maas","Yas","Calisma Saati"])

In [75]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176      -0.761422
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224 -0.000417       1.127900
Tugce   0.060668 -1.168144       0.500326

In [76]:
yeniDataFrame["Yas"]

Kadir     1.295176
Atlas     0.209048
Mehmet   -0.000417
Tugce    -1.168144
Name: Yas, dtype: float64

In [77]:
yeniDataFrame["Calisma Saati"]

Kadir    -0.761422
Atlas     0.522082
Mehmet    1.127900
Tugce     0.500326
Name: Calisma Saati, dtype: float64

In [78]:
yeniDataFrame[["Maas","Yas"]]

            Maas       Yas
Kadir   0.548051  1.295176
Atlas   1.763184  0.209048
Mehmet  0.968224 -0.000417
Tugce   0.060668 -1.168144

In [79]:
yeniDataFrame.loc["Kadir"]

Maas             0.548051
Yas              1.295176
Calisma Saati   -0.761422
Name: Kadir, dtype: float64

In [80]:
yeniDataFrame.loc["Tugce"]

Maas             0.060668
Yas             -1.168144
Calisma Saati    0.500326
Name: Tugce, dtype: float64

In [81]:
yeniDataFrame.iloc[3]

Maas             0.060668
Yas             -1.168144
Calisma Saati    0.500326
Name: Tugce, dtype: float64

In [82]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176      -0.761422
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224 -0.000417       1.127900
Tugce   0.060668 -1.168144       0.500326

In [83]:
yeniDataFrame["Emeklilik Yasi"] = yeniDataFrame["Yas"] + yeniDataFrame["Yas"]

In [84]:
yeniDataFrame

            Maas       Yas  Calisma Saati  Emeklilik Yasi
Kadir   0.548051  1.295176      -0.761422        2.590351
Atlas   1.763184  0.209048       0.522082        0.418096
Mehmet  0.968224 -0.000417       1.127900       -0.000833
Tugce   0.060668 -1.168144       0.500326       -2.336288

In [85]:
yeniDataFrame.drop("Emeklilik Yasi", axis = 1)

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176      -0.761422
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224 -0.000417       1.127900
Tugce   0.060668 -1.168144       0.500326

In [86]:
yeniDataFrame.drop(["Mehmet"] , axis = 0)

           Maas       Yas  Calisma Saati  Emeklilik Yasi
Kadir  0.548051  1.295176      -0.761422        2.590351
Atlas  1.763184  0.209048       0.522082        0.418096
Tugce  0.060668 -1.168144       0.500326       -2.336288

In [87]:
yeniDataFrame.drop(["Emeklilik Yasi"], axis = 1, inplace = True)

In [88]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176      -0.761422
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224 -0.000417       1.127900
Tugce   0.060668 -1.168144       0.500326

In [89]:
yeniDataFrame.loc["Kadir"]["Yas"]

np.float64(1.2951755155325553)

In [90]:
yeniDataFrame.loc["Atlas"]["Yas"]

np.float64(0.2090478483167673)

In [91]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176      -0.761422
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224 -0.000417       1.127900
Tugce   0.060668 -1.168144       0.500326

In [92]:
yeniDataFrame < 0

         Maas    Yas  Calisma Saati
Kadir   False  False           True
Atlas   False  False          False
Mehmet  False   True          False
Tugce   False   True          False

In [93]:
booleanFrame = yeniDataFrame < 0

In [94]:
booleanFrame

         Maas    Yas  Calisma Saati
Kadir   False  False           True
Atlas   False  False          False
Mehmet  False   True          False
Tugce   False   True          False

In [95]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176      -0.761422
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224 -0.000417       1.127900
Tugce   0.060668 -1.168144       0.500326

In [96]:
yeniDataFrame[booleanFrame]

        Maas       Yas  Calisma Saati
Kadir    NaN       NaN      -0.761422
Atlas    NaN       NaN            NaN
Mehmet   NaN -0.000417            NaN
Tugce    NaN -1.168144            NaN

In [97]:
yeniDataFrame[yeniDataFrame < 0]

        Maas       Yas  Calisma Saati
Kadir    NaN       NaN      -0.761422
Atlas    NaN       NaN            NaN
Mehmet   NaN -0.000417            NaN
Tugce    NaN -1.168144            NaN

In [98]:
yeniDataFrame[yeniDataFrame > 0]

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176            NaN
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224       NaN       1.127900
Tugce   0.060668       NaN       0.500326

In [99]:
yeniDataFrame[yeniDataFrame > 0]

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176            NaN
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224       NaN       1.127900
Tugce   0.060668       NaN       0.500326

In [101]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176      -0.761422
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224 -0.000417       1.127900
Tugce   0.060668 -1.168144       0.500326

In [102]:
yeniDataFrame[yeniDataFrame["Yas"] > 0]

           Maas       Yas  Calisma Saati
Kadir  0.548051  1.295176      -0.761422
Atlas  1.763184  0.209048       0.522082

In [104]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176      -0.761422
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224 -0.000417       1.127900
Tugce   0.060668 -1.168144       0.500326

In [105]:
yeniDataFrame.reset_index()

    index      Maas       Yas  Calisma Saati
0   Kadir  0.548051  1.295176      -0.761422
1   Atlas  1.763184  0.209048       0.522082
2  Mehmet  0.968224 -0.000417       1.127900
3   Tugce  0.060668 -1.168144       0.500326

In [106]:
yeniDataFrame

            Maas       Yas  Calisma Saati
Kadir   0.548051  1.295176      -0.761422
Atlas   1.763184  0.209048       0.522082
Mehmet  0.968224 -0.000417       1.127900
Tugce   0.060668 -1.168144       0.500326

In [107]:
yeniIndexListesi = ["Kad","Atl","Meh","Tug"]

In [108]:
yeniDataFrame["Yeni Index"] = yeniIndexListesi

In [109]:
yeniDataFrame

            Maas       Yas  Calisma Saati Yeni Index
Kadir   0.548051  1.295176      -0.761422        Kad
Atlas   1.763184  0.209048       0.522082        Atl
Mehmet  0.968224 -0.000417       1.127900        Meh
Tugce   0.060668 -1.168144       0.500326        Tug

In [110]:
yeniDataFrame.set_index("Yeni Index")

                Maas       Yas  Calisma Saati
Yeni Index
Kad         0.548051  1.295176      -0.761422
Atl         1.763184  0.209048       0.522082
Meh         0.968224 -0.000417       1.127900
Tug         0.060668 -1.168144       0.500326

In [111]:
yeniDataFrame.set_index("Yeni Index", inplace = True)

In [112]:
yeniDataFrame

                Maas       Yas  Calisma Saati
Yeni Index
Kad         0.548051  1.295176      -0.761422
Atl         1.763184  0.209048       0.522082
Meh         0.968224 -0.000417       1.127900
Tug         0.060668 -1.168144       0.500326

In [113]:
yeniDataFrame.loc["Kad"]

Maas             0.548051
Yas              1.295176
Calisma Saati   -0.761422
Name: Kad, dtype: float64

In [114]:
ilkIndexler = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]

In [115]:
icIndexler = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [116]:
 birlesmisIndex = list(zip(ilkIndexler,icIndexler))

In [118]:
birlesmisIndex

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [119]:
birlesmisIndex = pd.MultiIndex.from_tuples(birlesmisIndex)

In [120]:
type(birlesmisIndex)

pandas.core.indexes.multi.MultiIndex

In [121]:
birlesmisIndex

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [122]:
benimCizgiFilmListem = [[40,"A"],[10,"B"],[30,"C"],[9,"D"],[10,"E"],[11,"F"]]

In [123]:
cizgiFilmNumpyDizisi = np.array(benimCizgiFilmListem)

In [128]:
cizgiFilmDataFrame = pd.DataFrame(cizgiFilmNumpyDizisi, index = birlesmisIndex, columns = ["Yas","Meslek"])

In [129]:
cizgiFilmDataFrame

                   Yas Meslek
Simpson    Homer    40      A
           Bart     10      B
           Marge    30      C
South Park Cartman   9      D
           Kenny    10      E
           Kyle     11      F

In [131]:
cizgiFilmDataFrame.loc["Simpson"]

      Yas Meslek
Homer  40      A
Bart   10      B
Marge  30      C

In [132]:
cizgiFilmDataFrame.loc["South Park"]

        Yas Meslek
Cartman   9      D
Kenny    10      E
Kyle     11      F

In [134]:
cizgiFilmDataFrame.loc["South Park"].loc["Kenny"]

Yas       10
Meslek     E
Name: Kenny, dtype: object

In [135]:
cizgiFilmDataFrame.index.names = ["Film Adi", "Isim"]

In [136]:
cizgiFilmDataFrame

                   Yas Meslek
Film Adi   Isim
Simpson    Homer    40      A
           Bart     10      B
           Marge    30      C
South Park Cartman   9      D
           Kenny    10      E
           Kyle     11      F