In [4]:
import pandas as pd
import numpy as np

In [5]:
sozlukVerisi = {"Istanbul" : [30,29,np.nan], "Ankara" : [20,np.nan,25], "Izmir" : [40,39,38] }
havaDurumuDataFrame = pd.DataFrame(sozlukVerisi)

In [6]:
havaDurumuDataFrame

   Istanbul  Ankara  Izmir
0      30.0    20.0     40
1      29.0     NaN     39
2       NaN    25.0     38

In [7]:
havaDurumuDataFrame.dropna()

   Istanbul  Ankara  Izmir
0      30.0    20.0     40

In [8]:
havaDurumuDataFrame

   Istanbul  Ankara  Izmir
0      30.0    20.0     40
1      29.0     NaN     39
2       NaN    25.0     38

In [9]:
havaDurumuDataFrame.dropna(axis = 1)

   Izmir
0     40
1     39
2     38

In [10]:
yeniVeri = {"Istanbul" : [30,29,np.nan], "Ankara" : [20,np.nan,25], "Izmir" : [40,39,38], "Antaşya" : [45,np.nan,np.nan] }
yeniDataFrame = pd.DataFrame(yeniVeri)

In [11]:
yeniDataFrame

   Istanbul  Ankara  Izmir  Antaşya
0      30.0    20.0     40     45.0
1      29.0     NaN     39      NaN
2       NaN    25.0     38      NaN

In [12]:
yeniDataFrame.dropna(axis = 1, thresh = 2)

   Istanbul  Ankara  Izmir
0      30.0    20.0     40
1      29.0     NaN     39
2       NaN    25.0     38

In [13]:
yeniDataFrame

   Istanbul  Ankara  Izmir  Antaşya
0      30.0    20.0     40     45.0
1      29.0     NaN     39      NaN
2       NaN    25.0     38      NaN

In [14]:
yeniDataFrame.fillna(20)

   Istanbul  Ankara  Izmir  Antaşya
0      30.0    20.0     40     45.0
1      29.0    20.0     39     20.0
2      20.0    25.0     38     20.0

# groupby

In [18]:
maasSozlugu = { "Departman" : ["Yazılım","Yazılım","Pazarlama","Pazarlama","Hukuk","Hukuk"],
                "Calisan Ismi": ["Ahmet", "Mehmet","Kadir", "Burak", "Zeynep", "Fatma" ],
                "Maas" : [100,150,200,300,400,500]
               }

In [19]:
maasDataFrame = pd.DataFrame(maasSozlugu)

In [20]:
maasDataFrame

   Departman Calisan Ismi  Maas
0    Yazılım        Ahmet   100
1    Yazılım       Mehmet   150
2  Pazarlama        Kadir   200
3  Pazarlama        Burak   300
4      Hukuk       Zeynep   400
5      Hukuk        Fatma   500

In [25]:
groupObjesi = maasDataFrame.groupby("Departman")

In [29]:
groupObjesi.count()

           Calisan Ismi  Maas
Departman
Hukuk                 2     2
Pazarlama             2     2
Yazılım               2     2

In [30]:
groupObjesi.mean(numeric_only=True)

            Maas
Departman
Hukuk      450.0
Pazarlama  250.0
Yazılım    125.0

In [31]:
groupObjesi.min()

          Calisan Ismi  Maas
Departman
Hukuk            Fatma   400
Pazarlama        Burak   200
Yazılım          Ahmet   100

In [32]:
groupObjesi.max()

          Calisan Ismi  Maas
Departman
Hukuk           Zeynep   500
Pazarlama        Kadir   300
Yazılım         Mehmet   150

In [33]:
groupObjesi.describe()

           Maas
          count   mean        std    min    25%    50%    75%    max
Departman
Hukuk       2.0  450.0  70.710678  400.0  425.0  450.0  475.0  500.0
Pazarlama   2.0  250.0  70.710678  200.0  225.0  250.0  275.0  300.0
Yazılım     2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0