In [1]:
import numpy as np
import pandas as pd

In [4]:
sozluk1 = {"Isim" : ["Ahmet", "Mehmet", "Zeynep", "Kadir"], 
           "Spor" : ["Koşu", "Yüzme", "Koşu", "Basketbol"],
           "Kalori" : [100,200,300,400]
          }

In [6]:
dataFrame1 = pd.DataFrame(sozluk1,index = [0,1,2,3])

In [7]:
dataFrame1

     Isim       Spor  Kalori
0   Ahmet       Koşu     100
1  Mehmet      Yüzme     200
2  Zeynep       Koşu     300
3   Kadir  Basketbol     400

In [10]:
sozluk2 = {"Isim" : ["Osman", "Levent", "Aslı", "Fatma"], 
           "Spor" : ["Koşu", "Yüzme", "Koşu", "Basketbol"],
           "Kalori" : [200,100,50,300]
          }

In [11]:
dataFrame2 = pd.DataFrame(sozluk2,index = [4,5,6,7])

In [12]:
sozluk3 = {"Isim" : ["Ayse", "Mahmut", "Duygu", "Nur"], 
           "Spor" : ["Koşu", "Yüzme", "Badminton", "Tenis"],
           "Kalori" : [300,400,500,250]
          }

In [14]:
dataFrame3 = pd.DataFrame(sozluk3,index = [8,9,10,11])

In [15]:
dataFrame2

     Isim       Spor  Kalori
4   Osman       Koşu     200
5  Levent      Yüzme     100
6    Aslı       Koşu      50
7   Fatma  Basketbol     300

In [16]:
dataFrame3

      Isim       Spor  Kalori
8     Ayse       Koşu     300
9   Mahmut      Yüzme     400
10   Duygu  Badminton     500
11     Nur      Tenis     250

# concatenation

In [19]:
pd.concat([dataFrame1,dataFrame2,dataFrame3], axis = 1)

,Isim,Spor,Kalori,Isim,Spor,Kalori,Isim,Spor,Kalori
0,Ahmet,Koşu,100.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Mehmet,Yüzme,200.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Zeynep,Koşu,300.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Kadir,Basketbol,400.0,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,Osman,Koşu,200.0,NaN,NaN,NaN
5,NaN,NaN,NaN,Levent,Yüzme,100.0,NaN,NaN,NaN
6,NaN,NaN,NaN,Aslı,Koşu,50.0,NaN,NaN,NaN
7,NaN,NaN,NaN,Fatma,Basketbol,300.0,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,Ayse,Koşu,300.0
9,NaN,NaN,NaN,NaN,NaN,NaN,Mahmut,Yüzme,400.0
10,NaN,NaN,NaN,NaN,NaN,NaN,Duygu,Badminton,500.0
11,NaN,NaN,NaN,NaN,NaN,NaN,Nur,Tenis,250.0

In [18]:
pd.concat([dataFrame1,dataFrame2,dataFrame3], axis = 0)

      Isim       Spor  Kalori
0    Ahmet       Koşu     100
1   Mehmet      Yüzme     200
2   Zeynep       Koşu     300
3    Kadir  Basketbol     400
4    Osman       Koşu     200
5   Levent      Yüzme     100
6     Aslı       Koşu      50
7    Fatma  Basketbol     300
8     Ayse       Koşu     300
9   Mahmut      Yüzme     400
10   Duygu  Badminton     500
11     Nur      Tenis     250

## merge

In [20]:
mergeSozluk1 = {"Isim" : ["Ahmet", "Mehmet", "Zeynep", "Kadir"],
                "Spor" : ["Koşu", "Yüzme", "Koşu", "Basketbol"]
               }

In [21]:
mergeDataFrame1 = pd.DataFrame(mergeSozluk1)

In [22]:
mergeDataFrame1

     Isim       Spor
0   Ahmet       Koşu
1  Mehmet      Yüzme
2  Zeynep       Koşu
3   Kadir  Basketbol

In [23]:
mergeSozluk2 = {"Isim" : ["Ahmet", "Mehmet", "Zeynep", "Kadir"],
                "Kalori" : [100, 200, 150, 250]
               }

In [24]:
mergeDataFrame2 = pd.DataFrame(mergeSozluk2)

In [25]:
mergeDataFrame2

     Isim  Kalori
0   Ahmet     100
1  Mehmet     200
2  Zeynep     150
3   Kadir     250

In [26]:
pd.merge(mergeDataFrame1,mergeDataFrame2,on = "Isim")

     Isim       Spor  Kalori
0   Ahmet       Koşu     100
1  Mehmet      Yüzme     200
2  Zeynep       Koşu     150
3   Kadir  Basketbol     250

In [27]:
maasSozluk = {"Isim" : ["Kadir","Zeynep","Mehmet","Ahmet"],
              "Departman" : ["Yazılım","Satış","Pazarlama","Yazılım"],
              "Maas" : [200,300,400,500]
             }

In [28]:
maasDataFrame = pd.DataFrame(maasSozluk)

In [29]:
maasDataFrame

     Isim  Departman  Maas
0   Kadir    Yazılım   200
1  Zeynep      Satış   300
2  Mehmet  Pazarlama   400
3   Ahmet    Yazılım   500

In [33]:
maasDataFrame["Departman"].unique()

array(['Yazılım', 'Satış', 'Pazarlama'], dtype=object)

In [34]:
maasDataFrame["Departman"].nunique()

3

In [35]:
maasDataFrame["Departman"].value_counts()

Departman
Yazılım      2
Satış        1
Pazarlama    1
Name: count, dtype: int64

In [39]:
def bruttenNete(maas):
    return maas * 0.66

In [40]:
maasDataFrame["Maas"].apply(bruttenNete)

0    132.0
1    198.0
2    264.0
3    330.0
Name: Maas, dtype: float64

In [41]:
maasDataFrame.isnull()

    Isim  Departman   Maas
0  False      False  False
1  False      False  False
2  False      False  False
3  False      False  False

In [48]:
yeniBirVeri = {"Karakter Sinifi" : ["South Park","South Park","Simpson","Simpson","Simpson"],
               "Karakter Ismi" : ["Cartman","Kenny","Homer","Bart","Bart"],
               "Karakter Yas" : [9,10,50,20,10]
              }

In [49]:
karakterDataFrame = pd.DataFrame(yeniBirVeri)

In [50]:
karakterDataFrame

  Karakter Sinifi Karakter Ismi  Karakter Yas
0      South Park       Cartman             9
1      South Park         Kenny            10
2         Simpson         Homer            50
3         Simpson          Bart            20
4         Simpson          Bart            10

In [53]:
karakterDataFrame.pivot_table(values = "Karakter Yas", index = ["Karakter Sinifi", "Karakter Ismi"],aggfunc = np.sum)

C:\Users\kadir\AppData\Local\Temp\ipykernel_10564\1569349147.py:1: FutureWarning: The provided callable <function sum at 0x00000206B7791260> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  karakterDataFrame.pivot_table(values = "Karakter Yas", index = ["Karakter Sinifi", "Karakter Ismi"],aggfunc = np.sum)

                               Karakter Yas
Karakter Sinifi Karakter Ismi
Simpson         Bart                     30
                Homer                    50
South Park      Cartman                   9
                Kenny                    10